services:
  postgres:
    image: postgres:16-alpine
    container_name: alert-notification-postgres
    environment:
      POSTGRES_DB: AlertNotificationDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AlertNotificationDb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alert-notification-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=AlertNotificationDb;Username=postgres;Password=postgres"
      Teams__WebhookUrl: "https://default2eb49379eacd45d08fa1659e51aca7.a7.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/c3aac691cdc64d4882454a7630854a4d/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=HRrqIgfkxCwEJo3mvHlHH3I_6xJFdycyL6QIflF-Fao"
      Seq__Url: "http://seq:5341"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - default
      - docker_default

networks:
  default:
    name: alert-notification-service_default
  docker_default:
    external: true
    name: docker_default

volumes:
  postgres_data:
